[package]
name = "agner"
version = "0.2.8"
edition = "2021"

authors = ["Raman Hafiyatulin <r.gafiyatullin@me.com>"]
license = "MIT"
repository = "https://github.com/RGafiyatullin/agner"
description = "An actor toolkit inspired by Erlang/OTP"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sup"]

serde = ["agner-actors/serde"]

# Components
sup = ["dep:agner-sup"]
helm = ["dep:agner-helm"]

[dependencies]
agner-utils = { path = "../agner-utils", version = "=0.2.8" }
agner-actors = { path = "../agner-actors", version = "=0.2.8" }
agner-sup = { path = "../agner-sup", version = "=0.2.8", optional = true }
agner-helm = { path = "../agner-helm", version = "0.2.8", optional = true }
