[package]
name = "agner"
version = "0.2.10"
edition = "2021"

authors = ["Raman Hafiyatulin <r.gafiyatullin@me.com>"]
license = "MIT"
repository = "https://github.com/RGafiyatullin/agner"
description = "An actor toolkit inspired by Erlang/OTP"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# default = ["sup"]
default = ["full"]

full = ["sup", "helm", "test-actor"]

serde = ["agner-actors/serde"]

# Components
sup = ["dep:agner-sup"]
helm = ["dep:agner-helm"]
test-actor = ["dep:agner-test-actor"]

[dependencies]
agner-utils = { path = "../agner-utils", version = "=0.2.10" }
agner-actors = { path = "../agner-actors", version = "=0.2.10" }
agner-sup = { path = "../agner-sup", version = "=0.2.10", optional = true }
agner-helm = { path = "../agner-helm", version = "0.2.10", optional = true }
agner-test-actor = { path = "../agner-test-actor", version = "0.2.10", optional = true }

[dev-dependencies]
dotenv = "^0.15"
futures = "^0.3"
log = "^0.4"
pretty_env_logger = "^0.4"
thiserror = "^1"
tokio = {version = "^1", features = ["full"]}
