[package]
name = "agner"
version = "0.2.6"
edition = "2021"

authors = ["Raman Hafiyatulin <r.gafiyatullin@me.com>"]
license = "MIT"
repository = "https://github.com/RGafiyatullin/agner"
description = "An actor toolkit inspired by Erlang/OTP"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sup"]
sup = ["dep:agner-sup"]
serde = ["agner-actors/serde"]

[dependencies]
agner-utils = { path = "../agner-utils", version = "=0.2.6" }
agner-actors = { path = "../agner-actors", version = "=0.2.6" }
agner-sup = { path = "../agner-sup", version = "=0.2.6", optional = true }
