[package]
name = "agner-sup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agner-actors = { path = "../agner-actors", version = "^0.2" }
log = "^0.4"
tokio = {version = "^1", features = ["sync"]}

[dev-dependencies]
dotenv = "^0.15"
pretty_env_logger = "^0.4"
tokio = {version = "^1", features = ["macros", "rt-multi-thread", "sync", "time"]}
