[package]
name = "agner-sup"
version = "0.2.0"
edition = "2021"

authors = ["Raman Hafiyatulin <r.gafiyatullin@me.com>"]
license = "MIT"
repository = "https://github.com/RGafiyatullin/agner"
description = "An actor toolkit inspired by Erlang/OTP (supervisors)"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agner-actors = { path = "../agner-actors", version = "^0.2" }
arc-swap = "^1"
futures = "^0.3"
log = "^0.4"
pin-project = "^1"
tokio = {version = "^1", features = ["sync"]}

[dev-dependencies]
dotenv = "^0.15"
pretty_env_logger = "^0.4"
tokio = {version = "^1", features = ["macros", "rt-multi-thread", "sync", "time", "net"]}
