[package]
name = "agner-actors"
version = "0.2.0"
edition = "2021"

[dependencies]
dotenv = "^0.15"
futures = { version = "^0.3", features = ["bilock", "unstable"]}
log = "0.4"
pin-project = "^1"
pretty_env_logger = "^0.4"
thiserror = "^1"
tokio = {version = "^1", features = ["sync"]}

[dev-dependencies]
tokio = {version = "^1", features = ["macros", "rt-multi-thread", "sync", "time"]}
